export const ceoVaultAbi = [
  // ERC20 / ERC4626
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address" },
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "asset", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "totalAssets", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "convertToAssets",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToShares",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewDeposit",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewMint",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewWithdraw",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewRedeem",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxDeposit",
    inputs: [{ name: "receiver", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxMint",
    inputs: [{ name: "receiver", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxWithdraw",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxRedeem",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "redeem",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
  },

  // Governance + Agent functions
  {
    type: "function",
    name: "registerAgent",
    inputs: [
      { name: "metadataURI", type: "string" },
      { name: "ceoAmount", type: "uint256" },
      { name: "erc8004Id", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "deregisterAgent", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "registerProposal",
    inputs: [
      {
        name: "actions",
        type: "tuple[]",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
        ],
      },
      { name: "proposalURI", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vote",
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "support", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "execute",
    inputs: [
      { name: "proposalId", type: "uint256" },
      {
        name: "actions",
        type: "tuple[]",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "convertPerformanceFee",
    inputs: [
      {
        name: "actions",
        type: "tuple[]",
        components: [
          { name: "target", type: "address" },
          { name: "value", type: "uint256" },
          { name: "data", type: "bytes" },
        ],
      },
      { name: "minCeoOut", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "settleEpoch", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdrawFees", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "getClaimableFees",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },

  // Ownership + admin
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "recoverNative",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "addYieldVault", inputs: [{ name: "vault", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "removeYieldVault", inputs: [{ name: "vault", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "setWhitelistedTarget",
    inputs: [
      { name: "target", type: "address" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "setTreasury", inputs: [{ name: "newTreasury", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setEntryFeeBps", inputs: [{ name: "bps", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setPerformanceFeeBps", inputs: [{ name: "bps", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMinCeoStake", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setVaultCap", inputs: [{ name: "cap", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMaxDepositPerAddress", inputs: [{ name: "cap", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMinDeposit", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMinWithdraw", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setEpochDuration", inputs: [{ name: "duration", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setCeoGracePeriod", inputs: [{ name: "period", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMaxAgents", inputs: [{ name: "max", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMaxActions", inputs: [{ name: "max", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMaxDrawdownBps", inputs: [{ name: "bps", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "setERC8004Registries",
    inputs: [
      { name: "identity", type: "address" },
      { name: "reputation", type: "address" },
      { name: "validation", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // views
  { type: "function", name: "MAX_FEE_BPS", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MAX_PROPOSALS_PER_EPOCH", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_CEO_MISSED", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_PROPOSAL_PROFITABLE", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_PROPOSAL_SUBMITTED", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_PROPOSAL_UNPROFITABLE", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_PROPOSAL_WON", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_VOTED", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "SCORE_VOTED_WINNING_SIDE", inputs: [], outputs: [{ type: "int256" }], stateMutability: "view" },
  { type: "function", name: "paused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "i_ceoToken", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_owner", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_pendingOwner", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_treasury", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_entryFeeBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_performanceFeeBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_minCeoStake", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_vaultCap", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_maxDepositPerAddress", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_minDeposit", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_minWithdraw", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_epochDuration", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_ceoGracePeriod", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_maxAgents", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_maxActions", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_maxDrawdownBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_currentEpoch", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_epochStartTime", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "s_epochExecuted", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  {
    type: "function",
    name: "s_epochStartAssets",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_epochDeposits",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_epochWithdrawals",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  { type: "function", name: "s_pendingPerformanceFeeUsdc", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "s_claimableFees",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_isWhitelistedTarget",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_isYieldVault",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_yieldVaults",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_agentList",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_agents",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "ceoStaked", type: "uint256" },
      { name: "score", type: "int256" },
      { name: "erc8004Id", type: "uint256" },
      { name: "metadataURI", type: "string" },
      { name: "registeredAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_hasProposed",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_hasVoted",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_voteSupport",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  { type: "function", name: "s_erc8004Identity", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_erc8004Reputation", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "s_erc8004Validation", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "getTopAgent", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "getSecondAgent", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  {
    type: "function",
    name: "getWinningProposal",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [
      { name: "bestId", type: "uint256" },
      { name: "bestNet", type: "int256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLeaderboard",
    inputs: [],
    outputs: [
      { name: "agents", type: "address[]" },
      { name: "scores", type: "int256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProposalCount",
    inputs: [{ name: "epoch", type: "uint256" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProposal",
    inputs: [
      { name: "epoch", type: "uint256" },
      { name: "proposalId", type: "uint256" },
    ],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "proposalHash", type: "bytes32" },
          { name: "proposalURI", type: "string" },
          { name: "proposer", type: "address" },
          { name: "votesFor", type: "uint256" },
          { name: "votesAgainst", type: "uint256" },
          { name: "epoch", type: "uint256" },
          { name: "executed", type: "bool" },
          { name: "settled", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "getYieldVaults", inputs: [], outputs: [{ type: "address[]" }], stateMutability: "view" },
  { type: "function", name: "getAgentList", inputs: [], outputs: [{ type: "address[]" }], stateMutability: "view" },
  {
    type: "function",
    name: "getAgentInfo",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "ceoStaked", type: "uint256" },
      { name: "score", type: "int256" },
      { name: "erc8004Id", type: "uint256" },
      { name: "metadataURI", type: "string" },
      { name: "registeredAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "isVotingOpen", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getDeployedValue", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "requestRebalanceValidation",
    inputs: [
      { name: "validatorAddress", type: "address" },
      { name: "epoch", type: "uint256" },
      { name: "requestURI", type: "string" },
      { name: "requestHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // Events for execution log
  {
    type: "event",
    name: "ProposalRegistered",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "proposalHash", type: "bytes32", indexed: false },
      { name: "proposer", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Voted",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "voter", type: "address", indexed: true },
      { name: "support", type: "bool", indexed: false },
      { name: "weight", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Executed",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "proposalId", type: "uint256", indexed: false },
      { name: "ceo", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EpochSettled",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "profitable", type: "bool", indexed: false },
      { name: "revenue", type: "int256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PerformanceFeeAccrued",
    inputs: [
      { name: "epoch", type: "uint256", indexed: true },
      { name: "usdcAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PerformanceFeeConverted",
    inputs: [
      { name: "ceoAmount", type: "uint256", indexed: false },
      { name: "executor", type: "address", indexed: true },
    ],
  },
] as const;
